# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Zhe Li's Blog
url: "https://zh3li.github.io"
email: 
repository: "zh3li/zh3li.github.io"
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
github_username: zh3li
words_per_minute: 200
locale: "zh-CN"
minimal_mistakes_skin: default
search: true
atom_feed:
  hide: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

author:
  name   : "Zhe Li"
  avatar : "/assets/images/bio-photo-2.png"
  bio    : "欲买桂花同载酒，终不似，少年游。"
  home: "https://zh3li.github.io"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:lzlizhe@foxmail.com"  
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/zh3li"
    - label: "Steam"
      icon: "fab fa-fw fa-steam"
      url: "https://steamcommunity.com/profiles/76561198280862809/"
    - label: "Bilibili"
      icon: "fab fa-fw fa-bilibili"
      url: "https://space.bilibili.com/3181009"

# footer:
#   links:
#     - label: "GitHub"
#       icon: "fab fa-fw fa-github"
#       url: "https://github.com/zh3li"
#     - label: "Email"
#       icon: "fas fa-fw fa-envelope"
#       url: "mailto:lzlizhe@foxmail.com"
#     - label: "Steam"
#       icon: "fab fa-fw fa-steam"
#       url: "https://steamcommunity.com/profiles/76561198280862809/"
#     - label: "Bilibili"
#       icon: "fab fa-fw fa-bilibili"
#       url: "https://space.bilibili.com/3181009"
footer:
  since: 2019
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: false
      related: true
      toc: true
      toc_sticky: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

  # ===== 新增：Utterances 评论 =====
comments:
  provider: "utterances"

utterances:
  theme: "github-light"
  issue_term: pathname
  label: "comment"      # 如不用可删掉这一行